description: run on single machine

Environment: ubuntu 18.04, MPICH

instruction:
	run server: mpiexec -n 3 ./server
	run client: ./client [sleep interval] [key-range] [opearation-number] [put-percent]



description: run on amazon ec2 cluster

Environment: ubuntu 18.4, MPICH, nfs-server/nfs-client, opens

Instruction:
	run server on master node: mpiexec -n 3 -f machine file ./server
	run client on every node: ./client [sleep interval] [key-range] [opearation-number] [put-percent]
	

